version : '3.2'

services :

    python:
      build: 
        context: .
        dockerfile: Dockerfile-python
      image: python_setup:dev
      container_name: torch_python:dev
      volumes:
        - /home/saurabh/Documents/ml/mnist_digits/source:/home/docker/source
      command: tail -f /dev/null   
